config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "day_plans#index"

  resources :ingredients, :except => [:show]
  resources :recipes, :except => [:show] do
    resources :recipe_ingredients, :except => [:show]
  end
  resources :day_plans, :except => [:show] do
    resources :day_plan_recipes, :except => [:show]
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe

  def ingredient_name
    ingredient.name
  end

  def carbohydrates
    (ingredient.carbohydrates * amount / 100).round(2)
  end

  def fat
    (ingredient.fat * amount / 100).round(2)
  end

  def protein
    (ingredient.protein * amount / 100).round(2)
  end
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
  before_action :set_recipe_ingredient, only: [:show, :edit, :update, :destroy]
  before_action :set_recipe

  # GET /recipe_ingredients
  # GET /recipe_ingredients.json
  def index
    @recipe_ingredients = @recipe.recipe_ingredients
  end

  # GET /recipe_ingredients/1
  # GET /recipe_ingredients/1.json
  def show
  end

  # GET /recipe_ingredients/new
  def new
    @recipe_ingredient = RecipeIngredient.new
  end

  # GET /recipe_ingredients/1/edit
  def edit
  end

  # POST /recipe_ingredients
  # POST /recipe_ingredients.json
  def create
    @recipe_ingredient = @recipe.recipe_ingredients.new(recipe_ingredient_params)

    respond_to do |format|
      if @recipe_ingredient.save
        format.html { redirect_to [@recipe, @recipe_ingredient], notice: 'Recipe ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_ingredient }
      else
        format.html { render :new }
        format.json { render json: @recipe_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_ingredients/1
  # PATCH/PUT /recipe_ingredients/1.json
  def update
    respond_to do |format|
      if @recipe_ingredient.update(recipe_ingredient_params)
        format.html { redirect_to [@recipe, @recipe_ingredient], notice: 'Recipe ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_ingredient }
      else
        format.html { render :edit }
        format.json { render json: @recipe_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_ingredients/1
  # DELETE /recipe_ingredients/1.json
  def destroy
    @recipe_ingredient.destroy
    respond_to do |format|
      format.html { redirect_to recipe_ingredients_url, notice: 'Recipe ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_ingredient
      @recipe_ingredient = RecipeIngredient.find(params[:id])
    end

    def set_recipe
      @recipe = Recipe.find(params[:recipe_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_ingredient_params
      params.require(:recipe_ingredient).permit(:recipe_id, :ingredient_id, :amount)
    end
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/views/recipe_ingredients/_form.html.haml
= form_for([@recipe, @recipe_ingredient]) do |f|
  - if @recipe_ingredient.errors.any?
    #error_explanation
      %h2
        = pluralize(@recipe_ingredient.errors.count, "error")
        prohibited this recipe_ingredient from being saved:
      %ul
        - @recipe_ingredient.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :amount
    %br/
    = f.number_field :amount, :step => 0.1
  .field
    = f.label :ingredient_id
    %br/
    = f.collection_select :ingredient_id, Ingredient.all, :id, :name
    = link_to 'New Ingredient', new_ingredient_path
  .actions
    = f.submit

app/views/recipe_ingredients/edit.html.haml
%h1 Editing Recipe Ingredient
= render 'form'
= link_to 'Show', [@recipe, @recipe_ingredient]
|
= link_to 'Back', recipe_recipe_ingredients_path(@recipe)

app/views/recipe_ingredients/index.html.haml
%p#notice= notice
%h1 Listing Recipe Ingredients
%h2= @recipe.name

%table.table
  %thead
    %tr
      %th Ingredient
      %th Amount
      %th Carbohydrates
      %th Fat
      %th Protein
      %th{:colspan => "3"}
  %tbody
    - @recipe.recipe_ingredients.each do |recipe_ingredient|
      %tr
        %td= recipe_ingredient.ingredient_name
        %td= recipe_ingredient.amount
        %td= recipe_ingredient.carbohydrates
        %td= recipe_ingredient.fat
        %td= recipe_ingredient.protein
        %td= link_to 'Edit', edit_recipe_recipe_ingredient_path(@recipe, recipe_ingredient), class: 'btn btn-info'
        %td= link_to 'Destroy', [@recipe, recipe_ingredient], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

    %tr
      %td{:colspan => "2"}
      %td
        %strong
          = @recipe.carbohydrates
      %td
        %strong
          = @recipe.fat
      %td
        %strong
          = @recipe.protein
      %td{:colspan => "3"}

%br/
= link_to 'New Recipe ingredient', new_recipe_recipe_ingredient_path(@recipe)
%br/
= link_to 'Back to Recipes', recipes_path

app/views/recipe_ingredients/new.html.haml
%h1 New Recipe Ingredient
= render 'form'
= link_to 'Back', recipe_recipe_ingredients_path(@recipe)