config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "day_plans#index"

  resources :ingredients, :except => [:show]
  resources :recipes, :except => [:show] do
    resources :recipe_ingredients, :except => [:show]
  end
  resources :day_plans, :except => [:show] do
    resources :day_plan_recipes, :except => [:show]
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  def carbohydrates
    recipe_ingredients.map(&:carbohydrates).inject(0, :+).round(2)
  end

  def fat
    recipe_ingredients.map(&:fat).inject(0, :+).round(2)
  end

  def protein
    recipe_ingredients.map(&:protein).inject(0, :+).round(2)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.haml
= form_for(@recipe) do |f|
  - if @recipe.errors.any?
    #error_explanation
      %h2
        = pluralize(@recipe.errors.count, "error")
        prohibited this recipe from being saved:
      %ul
        - @recipe.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/recipes/edit.html.haml
%h1 Editing Recipe
= render 'form'
= link_to 'Show', @recipe
|
= link_to 'Back', recipes_path

app/views/recipes/index.html.haml
%p#notice= notice
%h1 Recipes
%table.table
  %thead
    %tr
      %th Name
      %th Carbohydrates
      %th Fat
      %th Protein
      %th{:colspan => "3"}
  %tbody
    - @recipes.each do |recipe|
      %tr
        %td= recipe.name
        %td= recipe.carbohydrates
        %td= recipe.fat
        %td= recipe.protein
        %td= link_to 'Ingredients', recipe_recipe_ingredients_path(recipe), class: 'btn btn-primary'
        %td= link_to 'Rename', edit_recipe_path(recipe), class: 'btn btn-info'
        %td= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

= link_to 'New Recipe', new_recipe_path, class: 'btn btn-default'

app/views/recipes/new.html.haml
%h1 New Recipe
= render 'form'
= link_to 'Back', recipes_path