config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "day_plans#index"

  resources :ingredients, :except => [:show]
  resources :recipes, :except => [:show] do
    resources :recipe_ingredients, :except => [:show]
  end
  resources :day_plans, :except => [:show] do
    resources :day_plan_recipes, :except => [:show]
  end
end

app/models/day_plan_recipe.rb
class DayPlanRecipe < ActiveRecord::Base
  belongs_to :recipe

  def recipe_name
    recipe.name
  end

  def carbohydrates
    recipe.carbohydrates
  end

  def fat
    recipe.fat
  end

  def protein
    recipe.protein
  end
end

app/controllers/day_plan_recipes_controller.rb
class DayPlanRecipesController < ApplicationController
  before_action :set_day_plan_recipe, only: [:show, :edit, :update, :destroy]
  before_action :set_day_plan

  # GET /day_plan_recipes
  # GET /day_plan_recipes.json
  def index
    @day_plan_recipes = @day_plan.day_plan_recipes
  end

  # GET /day_plan_recipes/1
  # GET /day_plan_recipes/1.json
  def show
  end

  # GET /day_plan_recipes/new
  def new
    @day_plan_recipe = DayPlanRecipe.new
  end

  # GET /day_plan_recipes/1/edit
  def edit
  end

  # POST /day_plan_recipes
  # POST /day_plan_recipes.json
  def create
    @day_plan_recipe = @day_plan.day_plan_recipes.new(day_plan_recipe_params)

    respond_to do |format|
      if @day_plan_recipe.save
        format.html { redirect_to [@day_plan, @day_plan_recipe], notice: 'Day plan recipe was successfully created.' }
        format.json { render :show, status: :created, location: @day_plan_recipe }
      else
        format.html { render :new }
        format.json { render json: @day_plan_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /day_plan_recipes/1
  # PATCH/PUT /day_plan_recipes/1.json
  def update
    respond_to do |format|
      if @day_plan_recipe.update(day_plan_recipe_params)
        format.html { redirect_to @day_plan_recipe, notice: 'Day plan recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @day_plan_recipe }
      else
        format.html { render :edit }
        format.json { render json: @day_plan_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /day_plan_recipes/1
  # DELETE /day_plan_recipes/1.json
  def destroy
    @day_plan_recipe.destroy
    respond_to do |format|
      format.html { redirect_to day_plan_day_plan_recipes_url(@day_plan), notice: 'Day plan recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day_plan_recipe
      @day_plan_recipe = DayPlanRecipe.find(params[:id])
    end

    def set_day_plan
      @day_plan = DayPlan.find(params[:day_plan_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_plan_recipe_params
      params.require(:day_plan_recipe).permit(:day_plan_id, :recipe_id)
    end
end

app/helpers/day_plan_recipes_helper.rb
module DayPlanRecipesHelper
end

app/views/day_plan_recipes/_form.html.haml
= form_for [@day_plan, @day_plan_recipe] do |f|
  - if @day_plan_recipe.errors.any?
    #error_explanation
      %h2= "#{pluralize(@day_plan_recipe.errors.count, "error")} prohibited this day_plan_recipe from being saved:"
      %ul
        - @day_plan_recipe.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :recipe_id
    = f.collection_select :recipe_id, Recipe.all, :id, :name
  .actions
    = f.submit 'Save'

app/views/day_plan_recipes/edit.html.haml
%h1 Editing day_plan_recipe

= render 'form'

= link_to 'Show', [@day_plan, @day_plan_recipe]
\|
= link_to 'Back', day_plan_day_plan_recipes_path(@day_plan)

app/views/day_plan_recipes/index.html.haml
%p#notice= notice
%h2= @day_plan.name

%table.table
  %thead
    %tr
      %th Recipe
      %th Carbohydrates
      %th Fat
      %th Protein
      %th
      %th
      %th

  %tbody
    - @day_plan_recipes.each do |day_plan_recipe|
      %tr
        %td= day_plan_recipe.recipe_name
        %td= day_plan_recipe.carbohydrates
        %td= day_plan_recipe.fat
        %td= day_plan_recipe.protein
        %td= link_to 'Ingredients', recipe_recipe_ingredients_path(day_plan_recipe), class: 'btn btn-primary'
        %td= link_to 'Rename', edit_day_plan_day_plan_recipe_path(@day_plan, day_plan_recipe), class: 'btn btn-info'
        %td= link_to 'Destroy', [@day_plan, day_plan_recipe], :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

    %tr
      %td
      %td
        %strong
          = @day_plan.carbohydrates
      %td
        %strong
          = @day_plan.fat
      %td
        %strong
          = @day_plan.protein
      %td{:colspan => "3"}

%br

= link_to 'Add Recipe', new_day_plan_day_plan_recipe_path(@day_plan), class: 'btn btn-default'

app/views/day_plan_recipes/new.html.haml
%h1 New day_plan_recipe

= render 'form'

= link_to 'Back', day_plan_day_plan_recipes_path(@day_plan)