config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "day_plans#index"

  resources :ingredients, :except => [:show]
  resources :recipes, :except => [:show] do
    resources :recipe_ingredients, :except => [:show]
  end
  resources :day_plans, :except => [:show] do
    resources :day_plan_recipes, :except => [:show]
  end
end

app/models/day_plan.rb
class DayPlan < ActiveRecord::Base
  has_many :day_plan_recipes

  def carbohydrates
    day_plan_recipes.map(&:carbohydrates).inject(0, :+).round(2)
  end

  def fat
    day_plan_recipes.map(&:fat).inject(0, :+).round(2)
  end

  def protein
    day_plan_recipes.map(&:protein).inject(0, :+).round(2)
  end
end

app/controllers/day_plans_controller.rb
class DayPlansController < ApplicationController
  before_action :set_day_plan, only: [:show, :edit, :update, :destroy]

  # GET /day_plans
  # GET /day_plans.json
  def index
    @day_plans = DayPlan.all
  end

  # GET /day_plans/1
  # GET /day_plans/1.json
  def show
  end

  # GET /day_plans/new
  def new
    @day_plan = DayPlan.new
  end

  # GET /day_plans/1/edit
  def edit
  end

  # POST /day_plans
  # POST /day_plans.json
  def create
    @day_plan = DayPlan.new(day_plan_params)

    respond_to do |format|
      if @day_plan.save
        format.html { redirect_to @day_plan, notice: 'Day plan was successfully created.' }
        format.json { render :show, status: :created, location: @day_plan }
      else
        format.html { render :new }
        format.json { render json: @day_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /day_plans/1
  # PATCH/PUT /day_plans/1.json
  def update
    respond_to do |format|
      if @day_plan.update(day_plan_params)
        format.html { redirect_to @day_plan, notice: 'Day plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @day_plan }
      else
        format.html { render :edit }
        format.json { render json: @day_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /day_plans/1
  # DELETE /day_plans/1.json
  def destroy
    @day_plan.destroy
    respond_to do |format|
      format.html { redirect_to day_plans_url, notice: 'Day plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day_plan
      @day_plan = DayPlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_plan_params
      params.require(:day_plan).permit(:name)
    end
end

app/helpers/day_plans_helper.rb
module DayPlansHelper
end

app/views/day_plans/_form.html.haml
= form_for @day_plan do |f|
  - if @day_plan.errors.any?
    #error_explanation
      %h2= "#{pluralize(@day_plan.errors.count, "error")} prohibited this day_plan from being saved:"
      %ul
        - @day_plan.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/day_plans/edit.html.haml
%h1 Editing day_plan

= render 'form'

= link_to 'Show', @day_plan
\|
= link_to 'Back', day_plans_path

app/views/day_plans/index.html.haml
%h1 Day Plans

%table.table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @day_plans.each do |day_plan|
      %tr
        %td= day_plan.name
        - day_plan.day_plan_recipes.each do |day_plan_recipe|
          %td= day_plan_recipe.recipe_name
        %td= link_to 'Recipes', day_plan_day_plan_recipes_path(day_plan), class: 'btn btn-primary'
        %td= link_to 'Rename', edit_day_plan_path(day_plan), class: 'btn btn-info'
        %td= link_to 'Destroy', day_plan, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

= link_to 'New Day plan', new_day_plan_path, class: 'btn btn-default'

app/views/day_plans/new.html.haml
%h1 New day_plan

= render 'form'

= link_to 'Back', day_plans_path